include: [ LevelResultsShared.yaml ]

# Properties about the file like its creator
fileProperties:
  creatorName: Mind Feast Games

# The Unity scene that will be loaded as background
sceneName: BlueWorld

cameraSettings:
  type: dynamic
  postProcessing:
    depthOfField: { enabled: true, focusDistance: 62.0, focalLength: 175.0, aperture: 1.0 }

grid: |
  gm,mm,__,dd,lr,__,__,  __,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  2b,__,__,__,2b,__,__,__,__,2b,__,__,__,2b,__,__,__,__,  __,2b,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,4d,__,__,__,__,__,__,__,__,__,__,__,  __,3h,__,__,
  __,__,__,__,__,__,__,  3h,__,__,__,3h,__,__,__,__,__,3h,__,__,3h,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,4a,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,

  __,__,__,__,__,__,__,  d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,s1,t1,u1,  __,__,__,__,
  __,__,__,__,__,__,__,  d2,e2,f2,g2,h2,i2,j2,k2,l2,m2,n2,o2,p2,q2,r2,s2,t2,u2,  __,__,__,3j,
  __,__,__,1b,__,__,__,  3h,e3,f3,g3,h3,i3,j3,k3,l3,m3,n3,o3,p3,q3,r3,s3,t3,u3,  __,__,__,__,
  __,__,__,__,__,__,__,  d4,e4,f4,g4,h4,i4,j4,k4,l4,m4,n4,o4,4b,q4,r4,s4,t4,u4,  __,__,__,3j,
  __,__,__,__,__,__,4d,  d5,e5,f5,g5,h5,i5,j5,k5,l5,m5,n5,o5,p5,q5,r5,s5,t5,u5,  __,__,__,__, 
  __,__,1b,__,__,__,__,  d6,e6,f6,g6,h6,i6,j6,k6,l6,m6,n6,o6,p6,q6,r6,s6,t6,u6,  __,__,__,3j,
  __,__,__,__,__,__,__,  d7,e7,f7,g7,h7,i7,j7,k7,l7,m7,n7,o7,p7,q7,r7,s7,t7,u7,  __,__,__,__,
  __,__,__,__,9o,__,4d,  d8,e8,f8,g8,h8,i8,j8,k8,l8,m8,n8,o8,p8,q8,r8,4p,t8,u8,  __,__,__,3j,
  __,__,__,__,__,__,__,  d9,e9,f9,g9,h9,i9,j9,k9,l9,m9,n9,o9,p9,q9,r9,s9,t9,u9,  __,1b,__,__,
  __,__,__,__,__,__,__,  da,ea,fa,7d,ha,ia,ja,ka,la,ma,na,oa,pa,qa,ra,sa,ta,ua,  __,__,__,__,
  __,__,__,__,__,__,__,  db,eb,fb,7b,hb,ib,jb,kb,lb,mb,nb,ob,pb,qb,rb,sb,tb,ub,  __,__,__,__,
  __,__,__,__,__,__,__,  3h,ec,fc,7b,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,  __,__,__,__,
  __,__,__,__,__,__,__,  dd,ed,fd,7b,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,  __,__,__,__,
  __,__,__,__,__,__,__,  de,ee,fe,7b,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,  __,__,__,__,
  __,__,__,__,__,__,__,  df,ef,ff,7b,hf,if,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,  __,__,__,__,
  __,__,__,__,__,__,__,  dg,eg,fg,7b,hg,ig,jg,kg,lg,mg,ng,og,pg,qg,rg,sg,tg,ug,  __,__,__,__,

  __,__,__,__,__,__,__,  __,__,__,7b,__,3h,__,__,4f,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,7b,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,2b,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,__,__,__,__,2b,__,__,__,__,__,__,__,  __,__,__,__,
  __,__,__,__,__,__,__,  __,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,__,  __,__,__,__

gridObjects:

  lr: [ levelResults ]
  dd: [ DIYManager ]
  mm: [ ShopMoneyManager ]
  TT: [ ShopTest ]
  
  d1: [  ]
  e1: [  ]
  f1: [  ]
  g1: [  ]
  h1: [  ]
  i1: [  ]
  j1: [  ]
  k1: [  ]
  l1: [  ]
  m1: [  ]
  n1: [  ]
  o1: [  ]
  p1: [  ]
  q1: [  ]
  r1: [  ]
  s1: [  ]
  t1: [  ]
  u1: [  ]

  d2: [  ]
  e2: [  ]
  f2: [  ]
  g2: [  ]
  h2: [  ]
  i2: [  ]
  j2: [  ]
  k2: [  ]
  l2: [  ]
  m2: [  ]
  n2: [  ]
  o2: [  ]
  p2: [  ]
  q2: [  ]
  r2: [  ]
  s2: [  ]
  t2: [  ]
  u2: [  ]

  d3: [  ]
  e3: [  ]
  f3: [  ]
  g3: [  ]
  h3: [  ]
  i3: [ wall_corner_se_Grey_Bricks, lightbulb_s ]
  j3: [ wall_s_Grey_Bricks, lightbulb_s ]
  k3: [ wall_s_Grey_Bricks, lightbulb_s ]
  l3: [ wall_s_Grey_Bricks, lightbulb_s, ticker_n ]
  m3: [ wall_s_Grey_Bricks, lightbulb_s ]
  n3: [ wall_s_rc_Grey_Bricks, lightbulb_s ]
  o3: [  ]
  p3: [  ]
  q3: [  ]
  r3: [  ]
  s3: [  ]
  t3: [  ]
  u3: [  ]

  d4: [  ]
  e4: [  ]
  f4: [  ]
  g4: [ blankFloor ]
  h4: [ blankFloor, wall_e_Grey_Bricks, lightbulb_e ]
  i4: [ f_Black_Tile, shrinkTestingTableFish, shrinkTutorialSign ]
  j4: [ f_White_Tile ]
  k4: [ f_Black_Tile, floordeco20, itemLandingPosBlocker, buyable_bed_upgrade1, buyable_bed_upgrade2, glassBarrierEdge_w ]
  l4: [ f_White_Tile, replayleveldeco2 ]
  m4: [ f_Black_Tile, nextleveldeco2 ]
  n4: [ f_White_Tile, wedge_s_White_LightTile ]
  o4: [ foundation_GreyWood_WallCorner_e ]
  p4: [  ]
  q4: [  ]
  r4: [  ]
  s4: [  ]
  t4: [  ]
  u4: [  ]

  d5: [  ]
  e5: [  ]
  f5: [  ]
  g5: [  ]
  h5: [ wall_e_Grey_Bricks, lightbulb_e ]
  i5: [ f_White_Tile, floordeco20, itemLandingPosBlocker, buyable_shrinkRay_dispenser ]
  j5: [ f_Black_Tile ]
  k5: [ f_White_Tile, floordeco20, itemLandingPosBlocker, buyable_pillcab_upgrade, glassBarrierEdge_w ]
  l5: [ f_Black_Tile ]
  m5: [ f_White_Tile ]
  n5: [ f_Black_Tile, shopItemDisplayTable, shineBurstParticles, item_childBedUpgrade1, item_childBedUpgrade2 ]
  o5: [ foundation_GreyWood_FullTile_e ]
  p5: [  ]
  q5: [  ]
  r5: [  ]
  s5: [  ]
  t5: [  ]
  u5: [  ]

  d6: [  ]
  e6: [  ]
  f6: [  ]
  g6: [  ]
  h6: [ wall_e_Grey_Bricks, lightbulb_e ]
  i6: [ f_Black_Tile, floordeco20, itemLandingPosBlocker, buyable_bed_child_upgrade1, buyable_bed_child_upgrade2, purchasedItemsSign ]
  j6: [ f_White_Tile ]
  k6: [ f_Black_Tile, floordeco20, itemLandingPosBlocker, buyable_applecab_upgrade, glassBarrierEdge_w ]
  l6: [ f_White_Tile ]
  m6: [ f_Black_Tile ]
  n6: [ f_White_Tile, shopItemDisplayTable, shineBurstParticles, item_shrinkRay ]
  o6: [ foundation_GreyWood_FullTile_e ]
  p6: [  ]
  q6: [  ]
  r6: [  ]
  s6: [  ]
  t6: [  ]
  u6: [  ]

  d7: [  ]
  e7: [  ]
  f7: [  ]
  g7: [  ]
  h7: [ wall_e_Grey_Bricks, lightbulb_e ]
  i7: [ f_White_Tile, floordeco20, itemLandingPosBlocker, buyable_bed_pet_upgrade1, buyable_bed_pet_upgrade2, glassBarrierEdge_s ]
  j7: [ f_Black_Tile ]
  k7: [ f_White_Tile, floordeco20, itemLandingPosBlocker, buyable_syringecab_upgrade, glassBarrierEdge_w, glassBarrierEdge_n ]
  l7: [ f_Black_Tile ]
  m7: [ f_White_Tile ]
  n7: [ f_Black_Tile, shopItemDisplayTable, shineBurstParticles, item_petBedUpgrade1, item_petBedUpgrade2 ]
  o7: [ foundation_GreyWood_FullTile_e ]
  p7: [  ]
  q7: [  ]
  r7: [  ]
  s7: [  ]
  t7: [  ]
  u7: [  ]

  d8: [  ]
  e8: [  ]
  f8: [  ]
  g8: [  ]
  h8: [ wall_e_Grey_Bricks, lightbulb_e ]
  i8: [ f_Black_Tile ]
  j8: [ f_White_Tile ]
  k8: [ f_Black_Tile ]
  l8: [ f_White_Tile ]
  m8: [ f_Black_Tile ]
  n8: [ f_White_Tile, shopItemDisplayTable, shineBurstParticles, item_syringeCabUpgrade ]
  o8: [ foundation_GreyWood_FullTile_e ]
  p8: [  ]
  q8: [  ]
  r8: [  ]
  s8: [  ]
  t8: [  ]
  u8: [  ]

  d9: [  ]
  e9: [  ]
  f9: [  ]
  g9: [  ]
  h9: [ wall_e_Grey_Bricks, lightbulb_e ]
  i9: [ f_White_Tile, atmHighValue, atmSpinningCoinHighValue ]
  j9: [ f_Black_Tile, floordeco4_w ]
  k9: [ f_White_Tile ]
  l9: [ f_Black_Tile ]
  m9: [ f_White_Tile ]
  n9: [ f_Black_Tile, shopItemDisplayTable, shineBurstParticles, item_appleCabUpgrade ]
  o9: [ foundation_GreyWood_FullTile_e ]
  p9: [  ]
  q9: [  ]
  r9: [  ]
  s9: [  ]
  t9: [  ]
  u9: [  ]

  da: [  ]
  ea: [  ]
  fa: [  ]
  ga: [  ]
  ha: [ wall_e_Grey_Bricks, lightbulb_e ]
  ia: [ f_Black_Tile, atmMediumValue, atmSpinningCoinMediumValue ]
  ja: [ f_White_Tile, floordeco4_w ]
  ka: [ f_Black_Tile ]
  la: [ f_White_Tile ]
  ma: [ f_Black_Tile ]
  na: [ f_White_Tile, shopItemDisplayTable, shineBurstParticles, item_pillCabUpgrade ]
  oa: [ foundation_GreyWood_FullTile_e ]
  pa: [  ]
  qa: [  ]
  ra: [  ]
  sa: [  ]
  ta: [  ]
  ua: [  ]

  db: [  ]
  eb: [  ]
  fb: [  ]
  gb: [  ]
  hb: [ wall_e_Grey_Bricks, lightbulb_e ]
  ib: [ f_White_Tile, atmLowValue, atmSpinningCoinLowValue ]
  jb: [ f_Black_Tile, floordeco4_w ]
  kb: [ f_White_Tile ]
  lb: [ f_Black_Tile ]
  mb: [ f_White_Tile ]
  nb: [ f_Black_Tile, shopItemDisplayTable, shineBurstParticles, item_bedUpgrade1, item_bedUpgrade2 ]
  ob: [ foundation_GreyWood_FullTile_e ]
  pb: [  ]
  qb: [  ]
  rb: [  ]
  sb: [  ]
  tb: [  ]
  ub: [  ]

  dc: [  ]
  ec: [  ]
  fc: [  ]
  gc: [  ]
  hc: [ wall_e_Grey_Bricks, lightbulb_e ]
  ic: [ f_Black_Tile ]
  jc: [ f_White_Tile ]
  kc: [ f_Black_Tile, nextleveldeco2 ]
  lc: [ f_White_Tile, nextleveldeco2 ]
  mc: [ f_Black_Tile ]
  nc: [ f_White_Tile ]
  oc: [ foundation_GreyWood_FullTile_e ]
  pc: [  ]
  qc: [  ]
  rc: [  ]
  sc: [  ]
  tc: [  ]
  uc: [  ]

  dd: [  ]
  ed: [  ]
  fd: [  ]
  gd: [  ]
  hd: [ wall_e_Grey_Bricks, lightbulb_e ]
  id: [ f_White_Tile, door_brown_e ]
  jd: [ f_Black_Tile ]
  kd: [ f_White_Tile, p1, floordeco21 ]
  ld: [ f_Black_Tile, p2, floordeco21 ]
  md: [ f_White_Tile ]
  nd: [ f_Black_Tile ]
  od: [ foundation_GreyWood_FullTile_e ]
  pd: [  ]
  qd: [  ]
  rd: [  ]
  sd: [  ]
  td: [  ]
  ud: [  ]

  de: [  ]
  ee: [  ]
  fe: [  ]
  ge: [  ]
  he: [ wall_e_lc_Grey_Bricks, lightbulb_e, walldeco1_e ]
  ie: [ f_Black_Tile, wedge_e_White_LightTile, blankCameraTarget ]
  je: [ f_White_Tile ]
  ke: [ f_Black_Tile, replayleveldeco2 ]
  le: [ f_White_Tile, replayleveldeco2 ]
  me: [ f_Black_Tile ]
  ne: [ f_White_Tile ]
  oe: [  ]
  pe: [  ]
  qe: [  ]
  re: [  ]
  se: [  ]
  te: [  ]
  ue: [  ]

  df: [  ]
  ef: [  ]
  ff: [  ]
  gf: [  ]
  hf: [  ]
  if: [ foundation_GreyWood_WallCorner_s ]
  jf: [ foundation_GreyWood_FullTile_s ]
  kf: [ foundation_GreyWood_FullTile_s ]
  lf: [ foundation_GreyWood_FullTile_s ]
  mf: [ foundation_GreyWood_FullTile_s ]
  nf: [ foundation_GreyWood_Corner_s ]
  of: [  ]
  pf: [  ]
  qf: [  ]
  rf: [  ]
  sf: [  ]
  tf: [  ]
  uf: [  ]

  dg: [  ]
  eg: [  ]
  fg: [  ]
  gg: [  ]
  hg: [  ]
  ig: [  ]
  jg: [  ]
  kg: [  ]
  lg: [  ]
  mg: [  ]
  ng: [  ]
  og: [  ]
  pg: [  ]
  qg: [  ]
  rg: [  ]
  sg: [  ]
  tg: [  ]
  ug: [  ]

objectDefinitions:
 
sounds:

globalData:
